#!/bin/ksh

# $Id: shplay.sh,v 1.1 2018/11/14 23:58:55 hajime Exp $

# shplay - play a file which have one byte data every line. it's originally
#          generated by xxd command from RAW format file. its format is
#          restricted such as sample rate for performance. but still much slow.
#
# Auther: Hajime Edakawa <hajime.edakawa@gmail.com>
# License: Public Domain
# Last Update: Nov, 2018

[[ -z $1 ]] && echo "Usage: $0 FILE" && exit

FILE=$1

RATE=8000
ENC=u8
FMT=raw

typeset table
integer -i10 i

i=0
while (( i < 256 )); do
	table[$i]=$(printf "\\\\x%X" $i)
	let i++
done

while read byte; do
	i=0x$byte
	echo ${table[$i]}
done <$FILE | xargs -n 1 printf "%b" $(cat) | aucat -r $RATE -e $ENC -h $FMT -i - 
